### PR TITLE
add bootstrap example

### PR DESCRIPTION
**Pull request by kevinhughes27**
@karlnapf I made a little sample of combing the doxygen output with bootstrap to make the manual like we discussed. I would imagine we can use some sort of templates with doxygen to do this directly from doxygen. Hopefully the bootstrap example is easy to understand!

### CODE REVIEW

**Comment by kevinhughes27** [comment]
Have a look at this: https://github.com/Velron/doxygen-bootstrapped, looks like we can add to the base template. I don't know how to handle the structural changes we want though (putting all the examples on the same page)

**Comment by karlnapf** [comment]
I was sick for a week, but now playing with this.
So it basically works. Could you elaborate a bit how you created this html file? Just copied together the existing ones?
I guess the next step would be to create this file from doxygen.

**Comment by kevinhughes27** [comment]
Yeah I just grabbed what I needed and made it up. I don't know much about
doxygen but you might be able to pass a template that would produce this.

**Comment by karlnapf** [comment]
I wonder whether we should not just do things by hand and not use Doxygen

We can keep the snippet system and markdown the same
 * Define language examples in the same way, with the ```#! [snippet_label] <code> #! [snippet_label]``` marks
 * Then write the doc entry in markdown (as the ```.md``` files here)

**Comment by karlnapf** [comment]
ah, lets meet in irc?

**Comment by kevinhughes27** [comment]
I am not on a computer right now

**Comment by karlnapf** [comment]
I see :) well ill answer here then

**Comment by karlnapf** [comment]
we basically just need a script that takes an example md file, puts in snippets and then generates html output. Another script then can iterate through all the md files and create a summary page which reflects the directory structure

**Comment by karlnapf** [comment]
Doxygen is an overkill for that

**Comment by karlnapf** [comment]
we could even just use markdowns ``` way to mark code snippets ```

**Comment by karlnapf** [comment]
I have looked at sphinx, and they also cannot do that.

I guess one way would be to simply generate the pages with doxygen, using a placeholder, and then "patch" the html files (that are already in correct structural form) afterwards by hand.

Though that is not very clean

**Comment by kevinhughes27** [comment]
jinja2 might be our friend here

**Comment by karlnapf** [comment]
I agree.

The thing with the div in the html is tricky though, as it requires filling in from multiple files.

**Comment by karlnapf** [comment]
Ok I played a bit more, I think we should use sphinx for this. It is so much easier to do things in there.
But thats a side detail.

More important: It is horrible to get all the content (i.e. different language examples in html) into *one* html file. Is it possible to do these tricks with content coming from different files?

It would be *so* much easier to just generate all the html file statically and then the top-bar changes the address suffix or so. Then we can just fire up multiple versions of the doxygen/sphinx --- one for each file, and done.

Getting any automated pasting together of these divs going is too much work I feel

**Comment by karlnapf** [comment]
In contrast, it is super easy to change the markdows/doxygen/sphinx files, just need to change filename/language highlighting

**Comment by kevinhughes27** [comment]
if we do some kind of templating then we should be able to collect sub files into one file

**Comment by karlnapf** [comment]
Summary then:

1. Write documentation (in doxygen/mardown or sphinx) Use templates for code-snippets like ```\snippet classifier/knn load_data```. Nothing conceptually needed here.
2. Clone the folder for every target language: ```examples_python, examples_octave, ... ```. In all actual files, the above ```\snippet``` line is replaced with (here: Python)

  ```
  \snippet classifier/knn.py load_data
  ```

  for doxygen, or



  ```
  .. literalinclude:: examples/knn.py
    :language: python
    :start-after: ![load_data]
    :end-before: ![load_data]
  ```

  for sphinx. How could this be done? By hand? Seems very easy, but could we also use jinj2 here?
3. Generate the documentation for all languages seperately via make. Produces html output. Straight forward.
4. Create another copy that will contain the html for the docs using all languages. In here, for each example page, merge the corresponding html files of step 3 into a single html page, using the ´´´<div>``` magic introduced by you. This step is unclear to me. We cannot use templates as the pages are very diverse. Doxygen/Sphinx can add the header that defines the tabs, but not fill with content. We would need a script that extracts the ´´´<div>``` of the listing of each html file and paste them into the existing one, repsecting the structure. How would you do this kevin?

**Comment by karlnapf** [comment]
Sphinx looks pretty combined with this:

https://github.com/karlnapf/shogun_manual/tree/master/sphinx/example_output

**Comment by karlnapf** [comment]
screenshot from 2015-03-21 16 14 54
screenshot from 2015-03-21 16 14 48

**Comment by karlnapf** [comment]
screenshot from 2015-03-21 16 14 54
screenshot from 2015-03-21 16 14 48

**Comment by karlnapf** [comment]
This might help:
http://sphinx-doc.org/templating.html

**Comment by karlnapf** [comment]
Just checked the template. Sphinx uses jinja2 to create its html files from a template. This way, we could do the above step 4 in two steps.

1. Modify the template to include all the bootstrap things in the header, and change the body to define the tabs.
2. Write a script that just inserts the bodies of the other html files to the appropriate place.

**Comment by karlnapf** [comment]
I managed to make sphinx create html files as we want them:
https://github.com/karlnapf/shogun_manual/commit/518a5204f687472156e12bca3628b2bd55f97c4c

Now the problem is to overwrite this ```body``` block in order to define them for python, octave, etc. And that these should be taken from other files. That might be beyond its capabilities, but it's a good start

**Comment by kevinhughes27** [comment]
looks like its coming along!

**Comment by lisitsyn** [comment]
Good job @karlnapf this looks very cool

**Comment by karlnapf** [comment]
Thanks!
Kevin, we might even get away without manual manipulation of the html files. In Sphinx we should be able to modify the body block..... From Python code maybe? Then we could just lie all the different .rst files and produce one body for each language from within Sphinx. Have to check the mechanics there. Maybe also have a look

Then Ann that remains is tempting the examples that the devs write so that all the different rst files are created. If that could also be done within the Sphinx make that would rock.

**Comment by karlnapf** [comment]
See also here for an easier way to include bootstrap:
https://github.com/ryan-roemer/sphinx-bootstrap-theme

**Comment by karlnapf** [comment]
And this allows to import markdown documents in sphinx:
https://github.com/sgenoud/remarkdown

We will need that to show our readme files

**Pull request merged**
